internal:
  - header: "Guide"
    link: "/guides"

  - header: "Reference"
    link: "/reference"

external:
  - header: "RickRoll"
    link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"


dropdowns:
  main_title: "Main Menu"
  items:
    - title: "Resources"
      type: external
      items:
        - title: "Docs"
          link: "https://example.com/docs"
        - title: "API"
          link: "https://example.com/api"

    - title: "Navigation"
      type: internal
      items:
        - title: "Home"
          link: "/home"
        - title: "About"
          link: "/about"

    - title: "Support"
      type: external
      items:
        - title: "FAQ"
          link: "https://example.com/faq"
        - title: "Contact"
          link: "https://example.com/contact"
