github_link: "https://github.com/Nareshix/Vai"

internals:
  - title: "Guide"
    link: "/guides"

  - title: "Reference"
    link: "/reference"

externals:
  - title: "RickRoll"
    link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"


dropdowns:
  - main_title: "Main Menu"
    items:
      - title: "Guide"
        type: internal
        link: "/guides"

      - title: "Resources"
        type: internal
        link: "/reference"

      - title: "Rickroll"
        type: external
        link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
