github_link: "https://github.com/Nareshix/Vai"
github_contribution_link: 'https://github.com/Nareshix/Vai/blob/main/docs/src/contributing.md'
github_repo_name: "vai"

internals:
  - title: "Guide"
    link: "/guides"

  - title: "Reference"
    link: "/reference"

externals:
  - title: "oursdasasdasdd mom"
    link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"


dropdowns:
  - main_title: "Main Menu or is it or is it not"
    items:
      - title: "Guide"
        type: internal
        link: "/guides"

      - title: "Resources"
        type: internal
        link: "/reference"

      - title: "Rickroll"
        type: external
        link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
