github_link: "https://github.com/Nareshix/vai"
edit_this_page_on_github_link: 'https://github.com/Nareshix/vai/tree/main/docs/src_md'
github_repo_name: "vai" # CASE SENSITIVE

internals:
  - title: "Introduction"
    link: "/introduction"


externals:
  - title: "Further Customisation"
    link: "/further-customisation"


dropdowns:
  - main_title: "Menu"
    items:
      - title: "example.com"
        type: "external"
        link: "https://example.com/"

      - title: "Further Customisation"
        type: "internal"
        link: "/further-customisation"
